# Site settings
title: Being Cyrus
email: beingcyruscomics@gmail.com

keywords: webcomic, comic, beingcyrus, beingcyruscomics
description: > # this means to ignore newlines until "baseurl:"
  A story of a serious Cyrus.


baseurl: http://www.beingcyr.us
url: / #Leave this, change the baseurl.

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, image_optim_cache.yml]

sidebar: false
categories: comics

# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

# Compress our Css
#sass:
#    style: :compressed

permalink: /:categories/:title/

#################################################
####CUSTOM

# Set default header image
header: yes
header_sm: images/header-sm.jpg
header_med: images/header-sm.jpg
header_large: images/header.jpg
header_xl: images/header.jpg

## Thumbnailer taken from https://github.com/chrisanthropic/jekyll-minimagick

# Autogenerate thumbs for comics
mini_magick:

#Create Thumbs for the Archive Page
    thumbnail:
      source: images/comics/
      destination: /images/comics/thumbs
      resize: "182x280^"

#Autogenerate smaller size for small screens
    small:
      source: images/comics/
      destination: /images/comics/small
      resize: "350x535^"

#### SEO Stuff
# Google Analytics
google_universal_analytics:
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image: /images/being-cyrus-logo.jpg #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
